apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
      app: api
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: ${DOCKER_REGISTRY}/demo/api:${TAG}
        name: api-node
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        